// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/alac_converter_api.dart';
import 'api/audio_api.dart';
import 'api/scanner.dart';
import 'api/simple.dart';
import 'api/uac2_api.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  Map<String, PlatformInt64> dco_decode_Map_String_i_64_None(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AlacAudioMetadata dco_decode_alac_audio_metadata(dynamic raw);

  @protected
  AudioCapabilityInfo dco_decode_audio_capability_info(dynamic raw);

  @protected
  AudioCapabilityType dco_decode_audio_capability_type(dynamic raw);

  @protected
  AudioEventType dco_decode_audio_event_type(dynamic raw);

  @protected
  AudioFileMetadata dco_decode_audio_file_metadata(dynamic raw);

  @protected
  AudioProgress dco_decode_audio_progress(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  AudioCapabilityInfo dco_decode_box_autoadd_audio_capability_info(dynamic raw);

  @protected
  AudioEventType dco_decode_box_autoadd_audio_event_type(dynamic raw);

  @protected
  AudioProgress dco_decode_box_autoadd_audio_progress(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw);

  @protected
  Uac2AudioFormat dco_decode_box_autoadd_uac_2_audio_format(dynamic raw);

  @protected
  Uac2DeviceInfo dco_decode_box_autoadd_uac_2_device_info(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw);

  @protected
  CrossfadeCurveType dco_decode_crossfade_curve_type(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AudioCapabilityType> dco_decode_list_audio_capability_type(dynamic raw);

  @protected
  List<AudioFileMetadata> dco_decode_list_audio_file_metadata(dynamic raw);

  @protected
  List<double> dco_decode_list_prim_f_32_loose(dynamic raw);

  @protected
  Float32List dco_decode_list_prim_f_32_strict(dynamic raw);

  @protected
  Uint16List dco_decode_list_prim_u_16_strict(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, PlatformInt64)> dco_decode_list_record_string_i_64(dynamic raw);

  @protected
  List<Uac2DeviceInfo> dco_decode_list_uac_2_device_info(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  AudioEventType? dco_decode_opt_box_autoadd_audio_event_type(dynamic raw);

  @protected
  AudioProgress? dco_decode_opt_box_autoadd_audio_progress(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  (String, PlatformInt64) dco_decode_record_string_i_64(dynamic raw);

  @protected
  ScanResult dco_decode_scan_result(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  Uac2AudioFormat dco_decode_uac_2_audio_format(dynamic raw);

  @protected
  Uac2ConnectionState dco_decode_uac_2_connection_state(dynamic raw);

  @protected
  Uac2DeviceCapabilities dco_decode_uac_2_device_capabilities(dynamic raw);

  @protected
  Uac2DeviceInfo dco_decode_uac_2_device_info(dynamic raw);

  @protected
  Uac2FallbackInfo dco_decode_uac_2_fallback_info(dynamic raw);

  @protected
  Uac2PipelineInfo dco_decode_uac_2_pipeline_info(dynamic raw);

  @protected
  Uac2TransferStats dco_decode_uac_2_transfer_stats(dynamic raw);

  @protected
  Uac2VolumeRange dco_decode_uac_2_volume_range(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  Map<String, PlatformInt64> sse_decode_Map_String_i_64_None(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AlacAudioMetadata sse_decode_alac_audio_metadata(
    SseDeserializer deserializer,
  );

  @protected
  AudioCapabilityInfo sse_decode_audio_capability_info(
    SseDeserializer deserializer,
  );

  @protected
  AudioCapabilityType sse_decode_audio_capability_type(
    SseDeserializer deserializer,
  );

  @protected
  AudioEventType sse_decode_audio_event_type(SseDeserializer deserializer);

  @protected
  AudioFileMetadata sse_decode_audio_file_metadata(
    SseDeserializer deserializer,
  );

  @protected
  AudioProgress sse_decode_audio_progress(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  AudioCapabilityInfo sse_decode_box_autoadd_audio_capability_info(
    SseDeserializer deserializer,
  );

  @protected
  AudioEventType sse_decode_box_autoadd_audio_event_type(
    SseDeserializer deserializer,
  );

  @protected
  AudioProgress sse_decode_box_autoadd_audio_progress(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  Uac2AudioFormat sse_decode_box_autoadd_uac_2_audio_format(
    SseDeserializer deserializer,
  );

  @protected
  Uac2DeviceInfo sse_decode_box_autoadd_uac_2_device_info(
    SseDeserializer deserializer,
  );

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  CrossfadeCurveType sse_decode_crossfade_curve_type(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AudioCapabilityType> sse_decode_list_audio_capability_type(
    SseDeserializer deserializer,
  );

  @protected
  List<AudioFileMetadata> sse_decode_list_audio_file_metadata(
    SseDeserializer deserializer,
  );

  @protected
  List<double> sse_decode_list_prim_f_32_loose(SseDeserializer deserializer);

  @protected
  Float32List sse_decode_list_prim_f_32_strict(SseDeserializer deserializer);

  @protected
  Uint16List sse_decode_list_prim_u_16_strict(SseDeserializer deserializer);

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, PlatformInt64)> sse_decode_list_record_string_i_64(
    SseDeserializer deserializer,
  );

  @protected
  List<Uac2DeviceInfo> sse_decode_list_uac_2_device_info(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  AudioEventType? sse_decode_opt_box_autoadd_audio_event_type(
    SseDeserializer deserializer,
  );

  @protected
  AudioProgress? sse_decode_opt_box_autoadd_audio_progress(
    SseDeserializer deserializer,
  );

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  (String, PlatformInt64) sse_decode_record_string_i_64(
    SseDeserializer deserializer,
  );

  @protected
  ScanResult sse_decode_scan_result(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  Uac2AudioFormat sse_decode_uac_2_audio_format(SseDeserializer deserializer);

  @protected
  Uac2ConnectionState sse_decode_uac_2_connection_state(
    SseDeserializer deserializer,
  );

  @protected
  Uac2DeviceCapabilities sse_decode_uac_2_device_capabilities(
    SseDeserializer deserializer,
  );

  @protected
  Uac2DeviceInfo sse_decode_uac_2_device_info(SseDeserializer deserializer);

  @protected
  Uac2FallbackInfo sse_decode_uac_2_fallback_info(SseDeserializer deserializer);

  @protected
  Uac2PipelineInfo sse_decode_uac_2_pipeline_info(SseDeserializer deserializer);

  @protected
  Uac2TransferStats sse_decode_uac_2_transfer_stats(
    SseDeserializer deserializer,
  );

  @protected
  Uac2VolumeRange sse_decode_uac_2_volume_range(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_Map_String_i_64_None(
    Map<String, PlatformInt64> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_alac_audio_metadata(
    AlacAudioMetadata self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_audio_capability_info(
    AudioCapabilityInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_audio_capability_type(
    AudioCapabilityType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_audio_event_type(
    AudioEventType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_audio_file_metadata(
    AudioFileMetadata self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_audio_progress(AudioProgress self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_audio_capability_info(
    AudioCapabilityInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_audio_event_type(
    AudioEventType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_audio_progress(
    AudioProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_uac_2_audio_format(
    Uac2AudioFormat self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_uac_2_device_info(
    Uac2DeviceInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_crossfade_curve_type(
    CrossfadeCurveType self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_audio_capability_type(
    List<AudioCapabilityType> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_audio_file_metadata(
    List<AudioFileMetadata> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_loose(
    List<double> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_f_32_strict(
    Float32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_16_strict(
    Uint16List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_i_64(
    List<(String, PlatformInt64)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_uac_2_device_info(
    List<Uac2DeviceInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_audio_event_type(
    AudioEventType? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_audio_progress(
    AudioProgress? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_usize(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_i_64(
    (String, PlatformInt64) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_scan_result(ScanResult self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_uac_2_audio_format(
    Uac2AudioFormat self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_uac_2_connection_state(
    Uac2ConnectionState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_uac_2_device_capabilities(
    Uac2DeviceCapabilities self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_uac_2_device_info(
    Uac2DeviceInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_uac_2_fallback_info(
    Uac2FallbackInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_uac_2_pipeline_info(
    Uac2PipelineInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_uac_2_transfer_stats(
    Uac2TransferStats self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_uac_2_volume_range(
    Uac2VolumeRange self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
