// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'alac_converter_api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `create_session`, `get_session`, `new`, `remove_session`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `SessionManager`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

/// Probe ALAC/M4A file and return metadata without creating a session
AlacAudioMetadata alacProbeMetadata({required List<int> fileBytes}) => RustLib
    .instance
    .api
    .crateApiAlacConverterApiAlacProbeMetadata(fileBytes: fileBytes);

/// Create a new conversion session and return session ID
BigInt alacCreateSession({required List<int> fileBytes}) => RustLib.instance.api
    .crateApiAlacConverterApiAlacCreateSession(fileBytes: fileBytes);

/// Get metadata for an active session
AlacAudioMetadata alacGetMetadata({required BigInt sessionId}) => RustLib
    .instance
    .api
    .crateApiAlacConverterApiAlacGetMetadata(sessionId: sessionId);

/// Get WAV header for the session
Uint8List alacGetWavHeader({required BigInt sessionId}) => RustLib.instance.api
    .crateApiAlacConverterApiAlacGetWavHeader(sessionId: sessionId);

/// Decode the next chunk of PCM data
///
/// Returns None when end of stream is reached
Uint8List? alacDecodeNextChunk({required BigInt sessionId}) => RustLib
    .instance
    .api
    .crateApiAlacConverterApiAlacDecodeNextChunk(sessionId: sessionId);

/// Seek to a specific time position in seconds
void alacSeek({required BigInt sessionId, required double timeSeconds}) =>
    RustLib.instance.api.crateApiAlacConverterApiAlacSeek(
      sessionId: sessionId,
      timeSeconds: timeSeconds,
    );

/// Close and cleanup a conversion session
void alacCloseSession({required BigInt sessionId}) => RustLib.instance.api
    .crateApiAlacConverterApiAlacCloseSession(sessionId: sessionId);

/// Convert entire ALAC/M4A file to WAV in memory (one-shot conversion)
///
/// For large files, prefer streaming with create_session + decode_next_chunk
Uint8List alacConvertToWav({required List<int> fileBytes}) => RustLib
    .instance
    .api
    .crateApiAlacConverterApiAlacConvertToWav(fileBytes: fileBytes);

/// Audio metadata exposed to Flutter
@freezed
sealed class AlacAudioMetadata with _$AlacAudioMetadata {
  const factory AlacAudioMetadata({
    required int sampleRate,
    required int channels,
    required int bitDepth,
    required BigInt durationSamples,
    required double durationSeconds,
  }) = _AlacAudioMetadata;
}
