// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'audio_api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `ensure_audio_engine`, `probe_output_sample_rate`, `read_audio_engine`, `with_audio_engine`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`

/// Check if native audio is available on this platform.
bool audioIsNativeAvailable() =>
    RustLib.instance.api.crateApiAudioApiAudioIsNativeAvailable();

/// Initialize the audio engine.
void audioInit() => RustLib.instance.api.crateApiAudioApiAudioInit();

/// Check if the audio engine is initialized.
bool audioIsInitialized() =>
    RustLib.instance.api.crateApiAudioApiAudioIsInitialized();

/// Enable or disable high-res mode. When enabled, the Rust engine is allowed
/// to initialize even if a DAC is not currently detected.
void audioSetHighResMode({required bool enabled}) =>
    RustLib.instance.api.crateApiAudioApiAudioSetHighResMode(enabled: enabled);

/// Update the current platform capability snapshot used for engine selection.
void audioSetCapabilityInfo({required AudioCapabilityInfo info}) =>
    RustLib.instance.api.crateApiAudioApiAudioSetCapabilityInfo(info: info);

/// Inspect the current capability snapshot after native detection and platform hints are merged.
Future<AudioCapabilityInfo> audioGetCapabilityInfo({
  int? preferredSampleRate,
}) => RustLib.instance.api.crateApiAudioApiAudioGetCapabilityInfo(
  preferredSampleRate: preferredSampleRate,
);

/// Return the currently selected engine.
String audioGetActiveEngine() =>
    RustLib.instance.api.crateApiAudioApiAudioGetActiveEngine();

/// Detect whether a DAC is present before attempting Rust engine initialization.
Future<bool> audioIsDacAvailable({int? preferredSampleRate}) =>
    RustLib.instance.api.crateApiAudioApiAudioIsDacAvailable(
      preferredSampleRate: preferredSampleRate,
    );

/// Play an audio file.
Future<void> audioPlay({required String path}) =>
    RustLib.instance.api.crateApiAudioApiAudioPlay(path: path);

/// Queue the next track for gapless playback.
Future<void> audioQueueNext({required String path}) =>
    RustLib.instance.api.crateApiAudioApiAudioQueueNext(path: path);

/// Pause playback.
Future<void> audioPause() => RustLib.instance.api.crateApiAudioApiAudioPause();

/// Resume playback after pause.
Future<void> audioResume() =>
    RustLib.instance.api.crateApiAudioApiAudioResume();

/// Stop playback completely.
Future<void> audioStop() => RustLib.instance.api.crateApiAudioApiAudioStop();

/// Seek to a position in the current track.
Future<void> audioSeek({required double positionSecs}) =>
    RustLib.instance.api.crateApiAudioApiAudioSeek(positionSecs: positionSecs);

/// Set the playback volume.
Future<void> audioSetVolume({required double volume}) =>
    RustLib.instance.api.crateApiAudioApiAudioSetVolume(volume: volume);

/// Set graphic EQ: enabled and 10 band gains in dB (order = 32,64,125,250,500,1k,2k,4k,8k,16k Hz).
Future<void> audioSetEqualizer({
  required bool enabled,
  required List<double> gainsDb,
}) => RustLib.instance.api.crateApiAudioApiAudioSetEqualizer(
  enabled: enabled,
  gainsDb: gainsDb,
);

/// Configure compressor settings for the native audio engine.
Future<void> audioSetCompressor({
  required bool enabled,
  required double thresholdDb,
  required double ratio,
  required double attackMs,
  required double releaseMs,
  required double makeupGainDb,
}) => RustLib.instance.api.crateApiAudioApiAudioSetCompressor(
  enabled: enabled,
  thresholdDb: thresholdDb,
  ratio: ratio,
  attackMs: attackMs,
  releaseMs: releaseMs,
  makeupGainDb: makeupGainDb,
);

/// Configure limiter settings for the native audio engine.
Future<void> audioSetLimiter({
  required bool enabled,
  required double inputGainDb,
  required double ceilingDb,
  required double releaseMs,
}) => RustLib.instance.api.crateApiAudioApiAudioSetLimiter(
  enabled: enabled,
  inputGainDb: inputGainDb,
  ceilingDb: ceilingDb,
  releaseMs: releaseMs,
);

/// Configure crossfade settings.
Future<void> audioSetCrossfade({
  required bool enabled,
  required double durationSecs,
}) => RustLib.instance.api.crateApiAudioApiAudioSetCrossfade(
  enabled: enabled,
  durationSecs: durationSecs,
);

/// Skip to the next queued track.
Future<void> audioSkipToNext() =>
    RustLib.instance.api.crateApiAudioApiAudioSkipToNext();

/// Set the playback speed.
Future<void> audioSetPlaybackSpeed({required double speed}) =>
    RustLib.instance.api.crateApiAudioApiAudioSetPlaybackSpeed(speed: speed);

/// Get the current playback speed.
double? audioGetPlaybackSpeed() =>
    RustLib.instance.api.crateApiAudioApiAudioGetPlaybackSpeed();

/// Get the current playback state.
String audioGetState() => RustLib.instance.api.crateApiAudioApiAudioGetState();

/// Get the current playback progress.
AudioProgress? audioGetProgress() =>
    RustLib.instance.api.crateApiAudioApiAudioGetProgress();

/// Poll for audio events (non-blocking).
AudioEventType? audioPollEvent() =>
    RustLib.instance.api.crateApiAudioApiAudioPollEvent();

/// Set the crossfade curve type.
Future<void> audioSetCrossfadeCurve({required CrossfadeCurveType curve}) =>
    RustLib.instance.api.crateApiAudioApiAudioSetCrossfadeCurve(curve: curve);

/// Get the audio engine's sample rate.
int? audioGetSampleRate() =>
    RustLib.instance.api.crateApiAudioApiAudioGetSampleRate();

/// Get the current track path.
String? audioGetCurrentPath() =>
    RustLib.instance.api.crateApiAudioApiAudioGetCurrentPath();

/// Get the number of audio channels.
BigInt? audioGetChannels() =>
    RustLib.instance.api.crateApiAudioApiAudioGetChannels();

/// Shutdown the audio engine.
Future<void> audioShutdown() =>
    RustLib.instance.api.crateApiAudioApiAudioShutdown();

class AudioCapabilityInfo {
  final List<AudioCapabilityType> capabilities;
  final String routeType;
  final String? routeLabel;
  final int? maxSampleRate;

  const AudioCapabilityInfo({
    required this.capabilities,
    required this.routeType,
    this.routeLabel,
    this.maxSampleRate,
  });

  @override
  int get hashCode =>
      capabilities.hashCode ^
      routeType.hashCode ^
      routeLabel.hashCode ^
      maxSampleRate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioCapabilityInfo &&
          runtimeType == other.runtimeType &&
          capabilities == other.capabilities &&
          routeType == other.routeType &&
          routeLabel == other.routeLabel &&
          maxSampleRate == other.maxSampleRate;
}

/// The currently available output capability classes for engine selection.
enum AudioCapabilityType { usbDac, hiResInternal, standard }

@freezed
sealed class AudioEventType with _$AudioEventType {
  const AudioEventType._();

  const factory AudioEventType.stateChanged({required String state}) =
      AudioEventType_StateChanged;
  const factory AudioEventType.progress({
    required double positionSecs,
    double? durationSecs,
    required double bufferLevel,
  }) = AudioEventType_Progress;
  const factory AudioEventType.trackEnded({required String path}) =
      AudioEventType_TrackEnded;
  const factory AudioEventType.crossfadeStarted({
    required String fromPath,
    required String toPath,
  }) = AudioEventType_CrossfadeStarted;
  const factory AudioEventType.error({required String message}) =
      AudioEventType_Error;
  const factory AudioEventType.nextTrackReady({required String path}) =
      AudioEventType_NextTrackReady;
}

/// Progress information returned to Dart.
class AudioProgress {
  /// Current position in seconds
  final double positionSecs;

  /// Total duration in seconds (if known)
  final double? durationSecs;

  /// Buffer fill level (0.0 to 1.0)
  final double bufferLevel;

  const AudioProgress({
    required this.positionSecs,
    this.durationSecs,
    required this.bufferLevel,
  });

  @override
  int get hashCode =>
      positionSecs.hashCode ^ durationSecs.hashCode ^ bufferLevel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioProgress &&
          runtimeType == other.runtimeType &&
          positionSecs == other.positionSecs &&
          durationSecs == other.durationSecs &&
          bufferLevel == other.bufferLevel;
}

/// Crossfade curve type for Dart.
enum CrossfadeCurveType { equalPower, linear, squareRoot, sCurve }
