// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../audio/crossfader.dart';
import '../audio/dsd_engine/dsd.dart';
import '../audio/engine.dart';
import '../audio/equalizer.dart';
import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'audio_api.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `ensure_audio_engine_excluded`, `ensure_audio_engine`, `prepare_decoder_source`, `read_audio_engine`, `record_dsd_native_failure`, `resolve_dsd_engine_sample_rate`, `resolve_requested_output_sample_rate`, `resolve_track_playback_output_sample_rate`, `verify_dop_passthrough`, `verify_dsd_engine_rate`, `with_audio_engine`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`

Future<DsdOutputMode> currentDsdOutputMode() =>
    RustLib.instance.api.crateApiAudioApiCurrentDsdOutputMode();

Future<DsdOutputMode> effectiveDsdOutputMode({
  required DsdOutputMode requested,
}) => RustLib.instance.api.crateApiAudioApiEffectiveDsdOutputMode(
  requested: requested,
);

Future<DsdOutputMode> effectiveDsdOutputModeForRate({
  required DsdOutputMode requested,
  DsdRate? dsdRate,
}) => RustLib.instance.api.crateApiAudioApiEffectiveDsdOutputModeForRate(
  requested: requested,
  dsdRate: dsdRate,
);

Future<void> setDsdTrackRate({required int rate}) =>
    RustLib.instance.api.crateApiAudioApiSetDsdTrackRate(rate: rate);

Future<String?> lastDsdNativeFailure() =>
    RustLib.instance.api.crateApiAudioApiLastDsdNativeFailure();

Future<void> clearDsdNativeFailure() =>
    RustLib.instance.api.crateApiAudioApiClearDsdNativeFailure();

Future<void> clearDsdTrackRate() =>
    RustLib.instance.api.crateApiAudioApiClearDsdTrackRate();

Future<int?> currentDsdTrackRate() =>
    RustLib.instance.api.crateApiAudioApiCurrentDsdTrackRate();

Future<void> setPendingVolume({required double volume}) =>
    RustLib.instance.api.crateApiAudioApiSetPendingVolume(volume: volume);

Future<double?> takePendingVolume() =>
    RustLib.instance.api.crateApiAudioApiTakePendingVolume();

Future<double> lastVolume() =>
    RustLib.instance.api.crateApiAudioApiLastVolume();

Future<void> setPendingCrossfade({
  required bool enabled,
  required double durationSecs,
}) => RustLib.instance.api.crateApiAudioApiSetPendingCrossfade(
  enabled: enabled,
  durationSecs: durationSecs,
);

Future<void> setPendingCrossfadeCurve({required CrossfadeCurve curve}) =>
    RustLib.instance.api.crateApiAudioApiSetPendingCrossfadeCurve(curve: curve);

Future<(bool, double, CrossfadeCurve)?> takePendingCrossfade() =>
    RustLib.instance.api.crateApiAudioApiTakePendingCrossfade();

Future<void> setPendingEqualizer({
  required bool enabled,
  required List<EqBandSpec> specs,
}) => RustLib.instance.api.crateApiAudioApiSetPendingEqualizer(
  enabled: enabled,
  specs: specs,
);

Future<(bool, List<EqBandSpec>)?> takePendingEqualizer() =>
    RustLib.instance.api.crateApiAudioApiTakePendingEqualizer();

Future<void> setPendingCrossfeed({required int level}) =>
    RustLib.instance.api.crateApiAudioApiSetPendingCrossfeed(level: level);

Future<int?> takePendingCrossfeed() =>
    RustLib.instance.api.crateApiAudioApiTakePendingCrossfeed();

/// Check if native audio is available on this platform.
bool audioIsNativeAvailable() =>
    RustLib.instance.api.crateApiAudioApiAudioIsNativeAvailable();

/// Initialize the audio engine.
void audioInit() => RustLib.instance.api.crateApiAudioApiAudioInit();

/// Check if the audio engine is initialized.
bool audioIsInitialized() =>
    RustLib.instance.api.crateApiAudioApiAudioIsInitialized();

/// Enable or disable high-res mode. When enabled, the Rust engine is allowed
/// to initialize even if a DAC is not currently detected.
void audioSetHighResMode({required bool enabled}) =>
    RustLib.instance.api.crateApiAudioApiAudioSetHighResMode(enabled: enabled);

/// Sync the Bit-perfect (DAP Internal) preference from Dart so the Rust engine manager
/// can factor it into engine selection and reuse decisions.
/// When toggled at runtime, the running engine's pipeline mode is switched
/// between Passthrough (bit-perfect) and Dsp (full processing) on DAP devices.
void audioSetDapBitPerfectEnabled({required bool enabled}) => RustLib
    .instance
    .api
    .crateApiAudioApiAudioSetDapBitPerfectEnabled(enabled: enabled);

/// Set the running Rust callback's base pipeline mode.
///
/// This is separate from the DAP preference because direct USB playback can
/// leave the engine in passthrough after bit-perfect is disabled.
void audioSetPipelineModePassthrough({required bool enabled}) => RustLib
    .instance
    .api
    .crateApiAudioApiAudioSetPipelineModePassthrough(enabled: enabled);

/// Sync the preferred Android audio API (AAudio / OpenSL ES / Auto) from Dart.
/// The change is staged on the engine manager and applied on the next engine
/// (re)initialization — the live stream is reopened when the preference no
/// longer matches the value the running engine was built with. On non-Android
/// targets this is a no-op (cpal has no AudioApi selection).
void audioSetAudioApi({required AudioApiPreference preference}) => RustLib
    .instance
    .api
    .crateApiAudioApiAudioSetAudioApi(preference: preference);

/// Read the currently-staged Android audio-API preference. Returns the string
/// key ("auto" / "aaudio" / "opensles") so Dart can mirror UI selection without
/// importing the generated enum mirror.
String audioGetAudioApi() =>
    RustLib.instance.api.crateApiAudioApiAudioGetAudioApi();

/// Toggle experimental 432 Hz tuning. When enabled the engine leaves bit-perfect
/// passthrough, runs the DSP path, and pins playback speed at 432/440.
void audioSet432HzTuningEnabled({required bool enabled}) => RustLib.instance.api
    .crateApiAudioApiAudioSet432HzTuningEnabled(enabled: enabled);

/// Set the DSD output mode from Dart. 0 = PCM decimation, 1 = DoP, 2 = Native, 3 = Auto.
void audioSetDsdOutputMode({required int mode}) =>
    RustLib.instance.api.crateApiAudioApiAudioSetDsdOutputMode(mode: mode);

/// Toggle DSD bit-reverse override. When on, inverts the bit-order normalization
/// so that MSB-first sources get reversed and LSB-first sources pass through.
/// Use this to diagnose white-noise from wrong bit order.
void audioSetDsdBitReverseOverride({required bool enabled}) => RustLib
    .instance
    .api
    .crateApiAudioApiAudioSetDsdBitReverseOverride(enabled: enabled);

/// Wire-packing variant for the DAP-internal native-DSD shim transport:
/// 0 = Auto/BE-MSB, 1 = LE-MSB, 2 = BE-LSB, 3 = LE-LSB. Wrong = hiss.
void audioSetSasWireVariant({required int variant}) => RustLib.instance.api
    .crateApiAudioApiAudioSetSasWireVariant(variant: variant);

/// Wire byte grouping (subslot width) for the DAP-internal native-DSD shim:
/// 0 = U32 (legacy), 1 = U16, 2 = U8 (byte-interleaved). Wrong = hiss.
void audioSetSasWireGrouping({required int grouping}) => RustLib.instance.api
    .crateApiAudioApiAudioSetSasWireGrouping(grouping: grouping);

/// Force the native-DSD wire byte order on the USB direct transport (DSD_U32
/// packing). Pass `None` to defer to the device quirk (auto). Use to diagnose
/// channel-swapped or noisy DSD from a wrong byte-order assumption.
void audioSetDsdBigEndianOverride({bool? value}) => RustLib.instance.api
    .crateApiAudioApiAudioSetDsdBigEndianOverride(value: value);

/// Force the native-DSD subslot size (1=DSD_U8, 2=DSD_U16, 4=DSD_U32) on the
/// USB direct transport. Pass `None` to defer to the descriptor / device quirk.
void audioSetDsdSubslotOverride({int? value}) => RustLib.instance.api
    .crateApiAudioApiAudioSetDsdSubslotOverride(value: value);

/// Update the current platform capability snapshot used for engine selection.
void audioSetCapabilityInfo({required AudioCapabilityInfo info}) =>
    RustLib.instance.api.crateApiAudioApiAudioSetCapabilityInfo(info: info);

/// Inspect the current capability snapshot after native detection and platform hints are merged.
Future<AudioCapabilityInfo> audioGetCapabilityInfo({
  int? preferredSampleRate,
}) => RustLib.instance.api.crateApiAudioApiAudioGetCapabilityInfo(
  preferredSampleRate: preferredSampleRate,
);

/// Return the currently selected engine.
String audioGetActiveEngine() =>
    RustLib.instance.api.crateApiAudioApiAudioGetActiveEngine();

Future<AudioRuntimeDebugState> audioGetRuntimeDebugState() =>
    RustLib.instance.api.crateApiAudioApiAudioGetRuntimeDebugState();

Future<AudioRuntimeDebugJsonState> audioGetRuntimeDebugJsonState() =>
    RustLib.instance.api.crateApiAudioApiAudioGetRuntimeDebugJsonState();

/// Detect whether a DAC is present before attempting Rust engine initialization.
Future<bool> audioIsDacAvailable({int? preferredSampleRate}) =>
    RustLib.instance.api.crateApiAudioApiAudioIsDacAvailable(
      preferredSampleRate: preferredSampleRate,
    );

/// Prepare the Rust audio engine for the requested output rate before playback starts.
Future<void> audioPrepareEngine({int? preferredSampleRate}) =>
    RustLib.instance.api.crateApiAudioApiAudioPrepareEngine(
      preferredSampleRate: preferredSampleRate,
    );

Future<AudioProbeFormat> audioProbeFormat({required String path}) =>
    RustLib.instance.api.crateApiAudioApiAudioProbeFormat(path: path);

/// Play an audio file.
Future<void> audioPlay({required String path}) =>
    RustLib.instance.api.crateApiAudioApiAudioPlay(path: path);

/// Queue the next track for gapless playback.
Future<void> audioQueueNext({required String path}) =>
    RustLib.instance.api.crateApiAudioApiAudioQueueNext(path: path);

/// Play a remote audio stream over HTTP. Range-support is assumed (caller
/// verifies `Accept-Ranges: bytes`); PCM only, no DSD/WavPack over HTTP.
/// Auth is carried via `headers` (e.g. WebDAV Basic) — Subsonic/Jellyfin embed
/// credentials in the URL query and pass an empty header map.
Future<void> audioPlayFromHttp({
  required String url,
  required Map<String, String> headers,
}) => RustLib.instance.api.crateApiAudioApiAudioPlayFromHttp(
  url: url,
  headers: headers,
);

/// Queue a remote HTTP stream as the next track for gapless playback.
Future<void> audioQueueNextFromHttp({
  required String url,
  required Map<String, String> headers,
}) => RustLib.instance.api.crateApiAudioApiAudioQueueNextFromHttp(
  url: url,
  headers: headers,
);

/// Pause playback.
Future<void> audioPause() => RustLib.instance.api.crateApiAudioApiAudioPause();

/// Resume playback after pause.
Future<void> audioResume() =>
    RustLib.instance.api.crateApiAudioApiAudioResume();

/// Stop playback completely.
Future<void> audioStop() => RustLib.instance.api.crateApiAudioApiAudioStop();

/// Seek to a position in the current track.
Future<void> audioSeek({required double positionSecs}) =>
    RustLib.instance.api.crateApiAudioApiAudioSeek(positionSecs: positionSecs);

/// Set the playback volume.
Future<void> audioSetVolume({required double volume}) =>
    RustLib.instance.api.crateApiAudioApiAudioSetVolume(volume: volume);

/// Set the effective ReplayGain (dB) for the current track and as the default
/// for subsequently spawned sources (next track, seek re-spawn). 0.0 = off.
///
/// Callers compute the final value — mode gain (track/album) + preamp +
/// clipping-prevention reduction — before calling. The engine applies it as a
/// per-source linear gain; a non-zero value forces the DSP path.
Future<void> audioSetReplaygain({required double gainDb}) =>
    RustLib.instance.api.crateApiAudioApiAudioSetReplaygain(gainDb: gainDb);

/// Set only the spawn-time default ReplayGain (dB): the running source keeps
/// its own gain while currently-playing. Used when pre-queueing the next
/// gapless track, whose gain is stamped on the newly spawned source.
Future<void> audioSetReplaygainDefault({required double gainDb}) => RustLib
    .instance
    .api
    .crateApiAudioApiAudioSetReplaygainDefault(gainDb: gainDb);

/// Set EQ: enabled and a variable list of band specs (real per-type biquads,
/// up to 31 bands). Graphic mode is expressed as 10 peaking specs.
Future<void> audioSetEqualizer({
  required bool enabled,
  required List<EqBandSpec> specs,
}) => RustLib.instance.api.crateApiAudioApiAudioSetEqualizer(
  enabled: enabled,
  specs: specs,
);

/// Set BS2B crossfeed level for the native audio engine.
/// 0 = Off, 1 = Default (BS2B middle preset), 2 = Crossfeed (high),
/// 3 = Crossfeed easy (gentle). 0 fully bypasses processing.
Future<void> audioSetCrossfeed({required int level}) =>
    RustLib.instance.api.crateApiAudioApiAudioSetCrossfeed(level: level);

/// Set pitch shift in semitones for the native audio engine (tempo preserved).
/// 0 = bypass. Range is clamped internally to ±12 semitones.
Future<void> audioSetPitchShiftSemitones({required double semitones}) => RustLib
    .instance
    .api
    .crateApiAudioApiAudioSetPitchShiftSemitones(semitones: semitones);

/// Configure compressor settings for the native audio engine.
Future<void> audioSetCompressor({
  required bool enabled,
  required double thresholdDb,
  required double ratio,
  required double attackMs,
  required double releaseMs,
  required double makeupGainDb,
}) => RustLib.instance.api.crateApiAudioApiAudioSetCompressor(
  enabled: enabled,
  thresholdDb: thresholdDb,
  ratio: ratio,
  attackMs: attackMs,
  releaseMs: releaseMs,
  makeupGainDb: makeupGainDb,
);

/// Configure limiter settings for the native audio engine.
Future<void> audioSetLimiter({
  required bool enabled,
  required double inputGainDb,
  required double ceilingDb,
  required double releaseMs,
}) => RustLib.instance.api.crateApiAudioApiAudioSetLimiter(
  enabled: enabled,
  inputGainDb: inputGainDb,
  ceilingDb: ceilingDb,
  releaseMs: releaseMs,
);

/// Configure spatial/time FX settings for the native audio engine.
Future<void> audioSetFx({
  required bool enabled,
  required double balance,
  required double tempo,
  required double damp,
  required double filterHz,
  required double delayMs,
  required double size,
  required double mix,
  required double feedback,
  required double width,
}) => RustLib.instance.api.crateApiAudioApiAudioSetFx(
  enabled: enabled,
  balance: balance,
  tempo: tempo,
  damp: damp,
  filterHz: filterHz,
  delayMs: delayMs,
  size: size,
  mix: mix,
  feedback: feedback,
  width: width,
);

/// Enable/disable the impulse-response convolver and set its wet/dry mix
/// (0.0 = dry, 1.0 = full IR).
Future<void> audioSetConvolver({required bool enabled, required double mix}) =>
    RustLib.instance.api.crateApiAudioApiAudioSetConvolver(
      enabled: enabled,
      mix: mix,
    );

/// Decode an impulse-response file, resample it to the engine rate and load it
/// into the convolver. Decoding runs on this thread (not the audio callback);
/// a failure leaves the previously-loaded IR untouched.
Future<void> audioLoadIr({required String path}) =>
    RustLib.instance.api.crateApiAudioApiAudioLoadIr(path: path);

/// Drop any loaded IR and disable the convolver.
Future<void> audioClearIr() =>
    RustLib.instance.api.crateApiAudioApiAudioClearIr();

/// Configure crossfade settings.
///
/// The engine's own `is_crossfade_allowed()` trigger gate (plus the Dart-side
/// processing policy) authoritatively decide whether crossfade runs; the old
/// passthrough guard here was redundant and self-defeating — it blocked the
/// very `crossfade_forces_dsp` flip that lets crossfade escape passthrough.
Future<void> audioSetCrossfade({
  required bool enabled,
  required double durationSecs,
}) => RustLib.instance.api.crateApiAudioApiAudioSetCrossfade(
  enabled: enabled,
  durationSecs: durationSecs,
);

/// Skip to the next queued track.
Future<void> audioSkipToNext() =>
    RustLib.instance.api.crateApiAudioApiAudioSkipToNext();

/// Set the playback speed.
Future<void> audioSetPlaybackSpeed({required double speed}) =>
    RustLib.instance.api.crateApiAudioApiAudioSetPlaybackSpeed(speed: speed);

/// Get the current playback speed.
double? audioGetPlaybackSpeed() =>
    RustLib.instance.api.crateApiAudioApiAudioGetPlaybackSpeed();

/// Get the current playback state.
String audioGetState() => RustLib.instance.api.crateApiAudioApiAudioGetState();

/// Get the current playback progress.
AudioProgress? audioGetProgress() =>
    RustLib.instance.api.crateApiAudioApiAudioGetProgress();

/// Poll for audio events (non-blocking).
AudioEventType? audioPollEvent() =>
    RustLib.instance.api.crateApiAudioApiAudioPollEvent();

/// Set the crossfade curve type.
Future<void> audioSetCrossfadeCurve({required CrossfadeCurveType curve}) =>
    RustLib.instance.api.crateApiAudioApiAudioSetCrossfadeCurve(curve: curve);

/// Get the audio engine's sample rate.
int? audioGetSampleRate() =>
    RustLib.instance.api.crateApiAudioApiAudioGetSampleRate();

/// Get the current track path.
String? audioGetCurrentPath() =>
    RustLib.instance.api.crateApiAudioApiAudioGetCurrentPath();

/// Get the number of audio channels.
BigInt? audioGetChannels() =>
    RustLib.instance.api.crateApiAudioApiAudioGetChannels();

/// Shutdown the audio engine.
Future<void> audioShutdown() =>
    RustLib.instance.api.crateApiAudioApiAudioShutdown();

class AudioCapabilityInfo {
  final List<AudioCapabilityType> capabilities;
  final String routeType;
  final String? routeLabel;
  final int? maxSampleRate;

  const AudioCapabilityInfo({
    required this.capabilities,
    required this.routeType,
    this.routeLabel,
    this.maxSampleRate,
  });

  @override
  int get hashCode =>
      capabilities.hashCode ^
      routeType.hashCode ^
      routeLabel.hashCode ^
      maxSampleRate.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioCapabilityInfo &&
          runtimeType == other.runtimeType &&
          capabilities == other.capabilities &&
          routeType == other.routeType &&
          routeLabel == other.routeLabel &&
          maxSampleRate == other.maxSampleRate;
}

/// The currently available output capability classes for engine selection.
enum AudioCapabilityType { usbDac, hiResInternal, standard }

@freezed
sealed class AudioEventType with _$AudioEventType {
  const AudioEventType._();

  const factory AudioEventType.stateChanged({required String state}) =
      AudioEventType_StateChanged;
  const factory AudioEventType.progress({
    required double positionSecs,
    double? durationSecs,
    required double bufferLevel,
  }) = AudioEventType_Progress;
  const factory AudioEventType.trackEnded({required String path}) =
      AudioEventType_TrackEnded;
  const factory AudioEventType.crossfadeStarted({
    required String fromPath,
    required String toPath,
  }) = AudioEventType_CrossfadeStarted;
  const factory AudioEventType.error({required String message}) =
      AudioEventType_Error;
  const factory AudioEventType.nextTrackReady({required String path}) =
      AudioEventType_NextTrackReady;
}

/// discover the actual sample rate before the USB engine is configured. Used by
/// Dart when song metadata lacks sampleRate/bitDepth, to avoid falling back to
/// just_audio and to avoid configuring the USB DAC clock at the wrong rate.
class AudioProbeFormat {
  final int sampleRate;
  final int channels;
  final int? bitsPerSample;

  const AudioProbeFormat({
    required this.sampleRate,
    required this.channels,
    this.bitsPerSample,
  });

  @override
  int get hashCode =>
      sampleRate.hashCode ^ channels.hashCode ^ bitsPerSample.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioProbeFormat &&
          runtimeType == other.runtimeType &&
          sampleRate == other.sampleRate &&
          channels == other.channels &&
          bitsPerSample == other.bitsPerSample;
}

/// Progress information returned to Dart.
class AudioProgress {
  /// Current position in seconds
  final double positionSecs;

  /// Total duration in seconds (if known)
  final double? durationSecs;

  /// Buffer fill level (0.0 to 1.0)
  final double bufferLevel;

  const AudioProgress({
    required this.positionSecs,
    this.durationSecs,
    required this.bufferLevel,
  });

  @override
  int get hashCode =>
      positionSecs.hashCode ^ durationSecs.hashCode ^ bufferLevel.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioProgress &&
          runtimeType == other.runtimeType &&
          positionSecs == other.positionSecs &&
          durationSecs == other.durationSecs &&
          bufferLevel == other.bufferLevel;
}

class AudioRuntimeDebugJsonState {
  final String managerEngine;
  final bool rustInitialized;
  final String? outputSignature;
  final int? sampleRate;
  final BigInt? channels;
  final String? outputStrategy;
  final int? requestedSampleRate;
  final int? actualSampleRate;
  final bool? resamplerActive;
  final bool? passthroughAllowed;
  final String? verificationReason;
  final bool? directUsbActive;
  final bool? directUsbVerified;
  final int? dsdSourceRate;
  final String? dsdEffectiveMode;
  final int? dsdWireRate;
  final String? dsdTransport;
  final String? activeAudioApi;

  const AudioRuntimeDebugJsonState({
    required this.managerEngine,
    required this.rustInitialized,
    this.outputSignature,
    this.sampleRate,
    this.channels,
    this.outputStrategy,
    this.requestedSampleRate,
    this.actualSampleRate,
    this.resamplerActive,
    this.passthroughAllowed,
    this.verificationReason,
    this.directUsbActive,
    this.directUsbVerified,
    this.dsdSourceRate,
    this.dsdEffectiveMode,
    this.dsdWireRate,
    this.dsdTransport,
    this.activeAudioApi,
  });

  @override
  int get hashCode =>
      managerEngine.hashCode ^
      rustInitialized.hashCode ^
      outputSignature.hashCode ^
      sampleRate.hashCode ^
      channels.hashCode ^
      outputStrategy.hashCode ^
      requestedSampleRate.hashCode ^
      actualSampleRate.hashCode ^
      resamplerActive.hashCode ^
      passthroughAllowed.hashCode ^
      verificationReason.hashCode ^
      directUsbActive.hashCode ^
      directUsbVerified.hashCode ^
      dsdSourceRate.hashCode ^
      dsdEffectiveMode.hashCode ^
      dsdWireRate.hashCode ^
      dsdTransport.hashCode ^
      activeAudioApi.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioRuntimeDebugJsonState &&
          runtimeType == other.runtimeType &&
          managerEngine == other.managerEngine &&
          rustInitialized == other.rustInitialized &&
          outputSignature == other.outputSignature &&
          sampleRate == other.sampleRate &&
          channels == other.channels &&
          outputStrategy == other.outputStrategy &&
          requestedSampleRate == other.requestedSampleRate &&
          actualSampleRate == other.actualSampleRate &&
          resamplerActive == other.resamplerActive &&
          passthroughAllowed == other.passthroughAllowed &&
          verificationReason == other.verificationReason &&
          directUsbActive == other.directUsbActive &&
          directUsbVerified == other.directUsbVerified &&
          dsdSourceRate == other.dsdSourceRate &&
          dsdEffectiveMode == other.dsdEffectiveMode &&
          dsdWireRate == other.dsdWireRate &&
          dsdTransport == other.dsdTransport &&
          activeAudioApi == other.activeAudioApi;
}

class AudioRuntimeDebugState {
  final String managerEngine;
  final bool rustInitialized;
  final String? outputSignature;
  final int? sampleRate;
  final BigInt? channels;

  const AudioRuntimeDebugState({
    required this.managerEngine,
    required this.rustInitialized,
    this.outputSignature,
    this.sampleRate,
    this.channels,
  });

  @override
  int get hashCode =>
      managerEngine.hashCode ^
      rustInitialized.hashCode ^
      outputSignature.hashCode ^
      sampleRate.hashCode ^
      channels.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioRuntimeDebugState &&
          runtimeType == other.runtimeType &&
          managerEngine == other.managerEngine &&
          rustInitialized == other.rustInitialized &&
          outputSignature == other.outputSignature &&
          sampleRate == other.sampleRate &&
          channels == other.channels;
}

/// Crossfade curve type for Dart.
enum CrossfadeCurveType { equalPower, linear, squareRoot, sCurve }
