// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `ape_cover_item`, `classify_scan_work`, `collect_file_entries`, `collect_playlist_file_entries`, `collect_scan_file_entries`, `directory_is_nomedia_blocked`, `extract_dff_artwork`, `extract_dff_metadata`, `extract_dsf_artwork`, `extract_dsf_metadata`, `extract_lofty_artwork`, `extract_lofty_metadata`, `extract_text_metadata_only`, `extract_wavpack_metadata`, `find_dff_id3_tag`, `id3_replaygains`, `is_in_nomedia_subtree`, `is_supported_audio_path`, `is_supported_playlist_path`, `lofty_replaygains`, `parse_rg_db`, `parse_rg_peak`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FileScanEntry`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

Future<ScanResult> scanRootDir({
  required String rootPath,
  required Map<String, PlatformInt64> knownFiles,
  required ScanOptions scanOptions,
}) => RustLib.instance.api.crateApiScannerScanRootDir(
  rootPath: rootPath,
  knownFiles: knownFiles,
  scanOptions: scanOptions,
);

Stream<ScanChunk> scanMusicLibrary({
  required String rootPath,
  required Map<String, PlatformInt64> knownFiles,
  required ScanOptions scanOptions,
}) => RustLib.instance.api.crateApiScannerScanMusicLibrary(
  rootPath: rootPath,
  knownFiles: knownFiles,
  scanOptions: scanOptions,
);

Future<List<String>> discoverPlaylistFiles({
  required String rootPath,
  required ScanOptions scanOptions,
}) => RustLib.instance.api.crateApiScannerDiscoverPlaylistFiles(
  rootPath: rootPath,
  scanOptions: scanOptions,
);

Future<List<String>> checkDeletedPaths({
  required String rootPath,
  required Map<String, PlatformInt64> knownFiles,
  required ScanOptions scanOptions,
}) => RustLib.instance.api.crateApiScannerCheckDeletedPaths(
  rootPath: rootPath,
  knownFiles: knownFiles,
  scanOptions: scanOptions,
);

/// Extract metadata for a single file on demand (used by the Dart metadata
/// fallback for formats MediaMetadataRetriever cannot decode). Returns None
/// when the file cannot be read or parsed.
Future<AudioFileMetadata?> extractFileMetadata({required String path}) =>
    RustLib.instance.api.crateApiScannerExtractFileMetadata(path: path);

Future<Uint8List?> extractEmbeddedArtwork({required String path}) =>
    RustLib.instance.api.crateApiScannerExtractEmbeddedArtwork(path: path);

class AudioFileMetadata {
  final String path;
  final String? title;
  final String? artist;
  final String? album;
  final BigInt? durationMs;
  final String format;
  final PlatformInt64 lastModified;
  final int? bitDepth;
  final int? sampleRate;
  final int? bitrate;
  final int? trackNumber;
  final int? discNumber;
  final BigInt fileSize;

  /// ReplayGain loudness gain for the track (dB).
  final double? replaygainTrackGain;

  /// ReplayGain track peak (linear, e.g. 0.977125).
  final double? replaygainTrackPeak;

  /// ReplayGain loudness gain for the whole album (dB).
  final double? replaygainAlbumGain;

  /// ReplayGain album peak (linear).
  final double? replaygainAlbumPeak;

  const AudioFileMetadata({
    required this.path,
    this.title,
    this.artist,
    this.album,
    this.durationMs,
    required this.format,
    required this.lastModified,
    this.bitDepth,
    this.sampleRate,
    this.bitrate,
    this.trackNumber,
    this.discNumber,
    required this.fileSize,
    this.replaygainTrackGain,
    this.replaygainTrackPeak,
    this.replaygainAlbumGain,
    this.replaygainAlbumPeak,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      title.hashCode ^
      artist.hashCode ^
      album.hashCode ^
      durationMs.hashCode ^
      format.hashCode ^
      lastModified.hashCode ^
      bitDepth.hashCode ^
      sampleRate.hashCode ^
      bitrate.hashCode ^
      trackNumber.hashCode ^
      discNumber.hashCode ^
      fileSize.hashCode ^
      replaygainTrackGain.hashCode ^
      replaygainTrackPeak.hashCode ^
      replaygainAlbumGain.hashCode ^
      replaygainAlbumPeak.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AudioFileMetadata &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          title == other.title &&
          artist == other.artist &&
          album == other.album &&
          durationMs == other.durationMs &&
          format == other.format &&
          lastModified == other.lastModified &&
          bitDepth == other.bitDepth &&
          sampleRate == other.sampleRate &&
          bitrate == other.bitrate &&
          trackNumber == other.trackNumber &&
          discNumber == other.discNumber &&
          fileSize == other.fileSize &&
          replaygainTrackGain == other.replaygainTrackGain &&
          replaygainTrackPeak == other.replaygainTrackPeak &&
          replaygainAlbumGain == other.replaygainAlbumGain &&
          replaygainAlbumPeak == other.replaygainAlbumPeak;
}

class ScanChunk {
  final List<AudioFileMetadata> newOrModified;
  final List<String> deletedPaths;
  final int totalFiles;
  final bool isComplete;

  const ScanChunk({
    required this.newOrModified,
    required this.deletedPaths,
    required this.totalFiles,
    required this.isComplete,
  });

  @override
  int get hashCode =>
      newOrModified.hashCode ^
      deletedPaths.hashCode ^
      totalFiles.hashCode ^
      isComplete.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanChunk &&
          runtimeType == other.runtimeType &&
          newOrModified == other.newOrModified &&
          deletedPaths == other.deletedPaths &&
          totalFiles == other.totalFiles &&
          isComplete == other.isComplete;
}

class ScanOptions {
  final bool filterNonMusicFilesAndFolders;

  const ScanOptions({required this.filterNonMusicFilesAndFolders});

  @override
  int get hashCode => filterNonMusicFilesAndFolders.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanOptions &&
          runtimeType == other.runtimeType &&
          filterNonMusicFilesAndFolders == other.filterNonMusicFilesAndFolders;
}

class ScanResult {
  final List<AudioFileMetadata> newOrModified;
  final List<String> deletedPaths;
  final int totalFiles;

  const ScanResult({
    required this.newOrModified,
    required this.deletedPaths,
    required this.totalFiles,
  });

  @override
  int get hashCode =>
      newOrModified.hashCode ^ deletedPaths.hashCode ^ totalFiles.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ScanResult &&
          runtimeType == other.runtimeType &&
          newOrModified == other.newOrModified &&
          deletedPaths == other.deletedPaths &&
          totalFiles == other.totalFiles;
}
