// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Returns whether the UAC 2.0 backend is available on this build.
/// True when built with the `uac2` feature; false otherwise.
bool uac2IsAvailable() => RustLib.instance.api.crateApiUac2ApiUac2IsAvailable();

/// Enumerates connected UAC 2.0 devices.
/// Returns an empty list when the `uac2` feature is disabled or when no devices are found.
List<Uac2DeviceInfo> uac2ListDevices() =>
    RustLib.instance.api.crateApiUac2ApiUac2ListDevices();

/// Information about a detected UAC 2.0 device (DAC/AMP).
class Uac2DeviceInfo {
  /// USB vendor ID
  final int vendorId;

  /// USB product ID
  final int productId;

  /// Device serial number (optional)
  final String? serial;

  /// Product name string
  final String productName;

  /// Manufacturer string
  final String manufacturer;

  const Uac2DeviceInfo({
    required this.vendorId,
    required this.productId,
    this.serial,
    required this.productName,
    required this.manufacturer,
  });

  @override
  int get hashCode =>
      vendorId.hashCode ^
      productId.hashCode ^
      serial.hashCode ^
      productName.hashCode ^
      manufacturer.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Uac2DeviceInfo &&
          runtimeType == other.runtimeType &&
          vendorId == other.vendorId &&
          productId == other.productId &&
          serial == other.serial &&
          productName == other.productName &&
          manufacturer == other.manufacturer;
}
